stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

deploy-job:
  image: docker:20.10.8
  stage: deploy
  services:
    - docker:20.10.8-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Deploying the application..."
    - docker build -t timpodszus/iberia-swp server/.
    - docker push timpodszus/iberia-swp
    - docker build -t timpodszus/iberia-db .
    - docker push timpodszus/iberia-db