services:
  db:
    image: timpodszus/iberia-db
    restart: always
    env_file: ./server/src/main/resources/.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: timpodszus/iberia-swp
    restart: always
    ports:
      - '8899:8899'
    expose:
      - '8899'
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  my-db: