services:
  db:
    image: git.swp-ibs.de:5050/swp/2024/ga/iberia
    restart: always
    env_file: .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: